apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kaushal-mental-models.fullname" . }}-config
  labels:
    {{- include "kaushal-mental-models.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
